### ISSUE TITLE
Not taking 2fa token

### ISSUE THREAD

**Issue by susenstoob** [boredazfcuk/docker-icloudpd#392]
So was able to intialize, download all photos, but now it wont connect on next syncs due to 2FA token not being accepted

Yes I logged into icloud.com without any popups (just my email and pass and got right in)

I have a seperate docker running a sync for my wife's account and that one has no issues, it just stays up and syncs regularly, so I assume the issue is something with my icloud/apple account vs the app, but I figured you guys could help.

2023-09-21 21:13:40 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.628 started *****
2023-09-21 21:13:40 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-09-21 21:13:41 INFO     Alpine Linux 3.18.2
2023-09-21 21:13:41 INFO     Python version: 3.11.4
2023-09-21 21:13:41 INFO     Loading configuration from: /config/icloudpd.conf
2023-09-21 21:13:48 INFO     Apple ID: REDACTED
2023-09-21 21:13:48 INFO     Authentication Type: MFA
2023-09-21 21:13:48 INFO     Cookie path: /config/REDACTED
2023-09-21 21:13:48 INFO     Cookie expiry notification period: 7
2023-09-21 21:13:48 INFO     Download destination directory: /home/user/iCloud
2023-09-21 21:13:48 INFO     Folder structure: {:%Y/%m/%d}
2023-09-21 21:13:48 INFO     Synchronisation interval: 86400
2023-09-21 21:13:48 INFO     Synchronisation delay (minutes): 0
2023-09-21 21:13:48 INFO     Set EXIF date/time: false
2023-09-21 21:13:48 INFO     Auto delete: false
2023-09-21 21:13:48 INFO     Delete after download: false
2023-09-21 21:13:48 INFO     Photo size: original
2023-09-21 21:13:48 INFO     Single pass mode: false
2023-09-21 21:13:48 INFO     Skip download check: false
2023-09-21 21:13:48 INFO     Skip live photos: false
2023-09-21 21:13:48 INFO     Number of most recently added photos to download: Download All Photos
2023-09-21 21:13:48 INFO     Downloading photos from album: Download All Photos
2023-09-21 21:13:48 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-09-21 21:13:48 INFO     Live photo size: original
2023-09-21 21:13:48 INFO     Skip videos: false
2023-09-21 21:13:48 INFO     Convert HEIC to JPEG: false
2023-09-21 21:13:48 INFO     Downloading from: icloud.com
2023-09-21 21:13:48 INFO     Authentication domain: com
2023-09-21 21:13:48 INFO     Ignore Synology extended attribute directories: Disabled
2023-09-21 21:13:48 INFO     Directory is writable: /config/python_keyring/
2023-09-21 21:13:48 INFO     Directory is writable: /home/user/.local/share/
2023-09-21 21:13:48 INFO     Check download directory mounted correctly...
2023-09-21 21:13:48 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-09-21 21:13:48 INFO     Directory is writable: /config/python_keyring/
2023-09-21 21:13:48 INFO     Directory is writable: /home/user/.local/share/
2023-09-21 21:13:48 INFO     Keyring file exists, continuing
Aborted!
2023-09-21 21:13:57 INFO     Albums available:
2023-09-21 21:13:57 INFO      - 2023-09-21 21:13:57 INFO     Two-step/two-factor authentication is required!
2023-09-21 21:13:57 INFO      -   0: SMS to REDACTED
2023-09-21 21:13:57 INFO      -   1: SMS to REDACTED
2023-09-21 21:13:57 INFO      -   2: Enter two-factor authentication code
2023-09-21 21:13:57 INFO      - Please choose an option: [0]: 
2023-09-21 21:13:57 INFO     Sync user: user
2023-09-21 21:13:57 INFO     Synchronisation starting at 21:13:57
2023-09-21 21:13:57 INFO     Keyring file exists, continuing
2023-09-21 21:13:57 INFO     Check download directory mounted correctly...
2023-09-21 21:13:57 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-09-21 21:13:57 INFO     Check for new files using password stored in keyring file
2023-09-21 21:13:57 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
  0: SMS to ********40
  1: SMS to ********80
  2: Enter two-factor authentication code
Please choose an option: [0]: 2023-09-21 21:13:59 ERROR    Failed check for new files files
2023-09-21 21:13:59 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2023-09-21 21:13:59 ERROR    Error debugging info:
2023-09-21 21:13:59 ERROR    Aborted!
2023-09-21 21:13:59 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023-09-21 21:13:59 INFO     Web cookie expires: 2023-11-13 @ 04:02:51
2023-09-21 21:13:59 INFO     Two factor authentication cookie expires: 2023-12-10 @ 04:48:19
2023-09-21 21:13:59 INFO     Days remaining until expiration: 79
2023-09-21 21:13:59 INFO     Synchronisation ended at 21:13:59
2023-09-21 21:13:59 INFO     Total time taken: 00:00:02
2023-09-21 21:13:59 INFO     Next synchronisation at 21:13:57

**Comment by susenstoob** [comment]
> You will need to map the /config directory to different locations for each user. I've seen similar problems when people have specified the same location for /config when using multiple containers, so the second container overwrites the first containers config.

Thanks! However, they are using 2 different locations for /config. See the screenshot below showing that I have 2 seperate Volumes for each container in 2 differnet locations.

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/127359080/7c9ffe85-298c-459e-9fa0-b33b01ebd77e)

**Comment by boredazfcuk** [comment]
Is the same volume mapped to both containers though?

I run four containers which sync every 4 hours. I only ever get prompted for Apple MFA when my cookies expire, or if I restart the container multiple times in quick succession.

I used to get it quite often a while back. It was due to the account being locked and needing to log on to iCloud and go through the account unlock procedure. It was resolved when I changed the Apple ID to a different e-mail address. I can only presume that the account was frequently being brute forced by someone/something.

**Comment by susenstoob** [comment]
> Is the same volume mapped to both containers though?
> 
> I run four containers which sync every 4 hours. I only ever get prompted for Apple MFA when my cookies expire, or if I restart the container multiple times in quick succession.
> 
> I used to get it quite often a while back. It was due to the account being locked and needing to log on to iCloud and go through the account unlock procedure. It was resolved when I changed the Apple ID to a different e-mail address. I can only presume that the account was frequently being brute forced by someone/something.

No, each container has its own unique volume and each volume is pointing to a unqiue directory. I even confirmed by logging into both containers via console and writing a test file in each config dir, both wrote a unqiue file and the others file did not appear. I rebooted the containers and each of the test file remained and are still seperate. So I have confirmed there is no correlation between each others config.

Additionally, just to make sure 1 container is not interrupting the other. I turned off the working container, rebuilt my non working container, the first sync worked, and then the same 2fa failure exists on subsequent syncs even with the working container still turned off.

Again, this feels like an issue with my icloud account, but I cannot find anything in my account that would prohibit from the 2fa tokens working.

**Comment by boredazfcuk** [comment]
```
2023-09-21 21:13:57 INFO Albums available:
```

The latest versions of the container should 't show this info. Can you update to latest and see if you still see the same behaviour?

**Comment by susenstoob** [comment]
> ```
> 2023-09-21 21:13:57 INFO Albums available:
> ```
> 
> The latest versions of the container should 't show this info. Can you update to latest and see if you still see the same behaviour?

Sadly behavior still exists post container upgrade. It does look/act differently, but in the end, I got the standard Apple MFA popup on my phone and it didnt sync or pull down any new items.

2023-10-02 13:35:08 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.657 started *****
2023-10-02 13:35:08 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023-10-02 13:35:08 INFO     Alpine Linux 3.18.3
2023-10-02 13:35:08 INFO     Python version: 3.11.5
2023-10-02 13:35:08 INFO     Loading configuration from: /config/icloudpd.conf
2023-10-02 13:35:20 INFO     Apple ID: REDACTED
2023-10-02 13:35:20 INFO     Authentication Type: MFA
2023-10-02 13:35:20 INFO     Cookie path: /config/REDACTED
2023-10-02 13:35:20 INFO     Cookie expiry notification period: 7
2023-10-02 13:35:20 INFO     Download destination directory: /home/user/iCloud
2023-10-02 13:35:20 INFO     Folder structure: {:%Y/%m/%d}
2023-10-02 13:35:20 INFO     Synchronisation interval: 86400
2023-10-02 13:35:20 INFO     Synchronisation delay (minutes): 0
2023-10-02 13:35:20 INFO     Set EXIF date/time: false
2023-10-02 13:35:20 INFO     Auto delete: false
2023-10-02 13:35:20 INFO     Delete after download: false
2023-10-02 13:35:20 INFO     Photo size: original
2023-10-02 13:35:20 INFO     Single pass mode: false
2023-10-02 13:35:20 INFO     Skip download check: false
2023-10-02 13:35:20 INFO     Skip live photos: false
2023-10-02 13:35:20 INFO     Number of most recently added photos to download: Download All Photos
2023-10-02 13:35:20 INFO     Downloading photos from: Download All Photos
2023-10-02 13:35:20 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023-10-02 13:35:20 INFO     Live photo size: original
2023-10-02 13:35:20 INFO     Skip videos: false
2023-10-02 13:35:20 INFO     Convert HEIC to JPEG: false
2023-10-02 13:35:20 INFO     Downloading from: icloud.com
2023-10-02 13:35:20 INFO     Authentication domain: com
2023-10-02 13:35:20 INFO     Ignore Synology extended attribute directories: Disabled
2023-10-02 13:35:21 INFO     Directory is writable: /config/python_keyring/
2023-10-02 13:35:21 INFO     Check download directory mounted correctly...
2023-10-02 13:35:21 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-10-02 13:35:21 INFO     Directory is writable: /config/python_keyring/
2023-10-02 13:35:21 INFO     Keyring file exists, continuing
2023-10-02 13:35:21 INFO     Sync user: user
2023-10-02 13:35:21 INFO     Synchronisation starting at 13:35:21
2023-10-02 13:35:21 INFO     Keyring file exists, continuing
2023-10-02 13:35:21 INFO     Check download directory mounted correctly...
2023-10-02 13:35:21 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2023-10-02 13:35:21 INFO     Check for new files using password stored in keyring file
2023-10-02 13:35:21 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
  0: SMS to *********0
  1: SMS to *********0
  2: Enter two-factor authentication code
Please choose an option: [0]: 2023-10-02 13:35:26 INFO     Check successful
2023-10-02 13:35:26 INFO     New files detected: 4
2023-10-02 13:35:27 DEBUG    Authenticating...
2023-10-02 13:35:28 INFO     Two-step/two-factor authentication is required
  0: SMS to *********0
  1: SMS to *********0
  2: Enter two-factor authentication code
Please choose an option: [0]: 2023-10-02 13:35:32 INFO     Synchronisation complete for user
2023-10-02 13:35:32 INFO     Web cookie expires: 2023-11-13 @ 04:02:51
2023-10-02 13:35:32 INFO     Multifactor authentication cookie expires: 2023-12-10 @ 04:48:19
2023-10-02 13:35:32 INFO     Days remaining until expiration: 68
2023-10-02 13:35:32 INFO     Synchronisation ended at 13:35:32
2023-10-02 13:35:32 INFO     Total time taken: 00:00:11
2023-10-02 13:35:32 INFO     Next synchronisation at 13:35:21

**Comment by boredazfcuk** [comment]
Can you set `debug_logging=true` in your `/config/icloudpd.conf` file and grab another log?

Also, have you changed your password recently? You'll need to run `sync-icloud.sh --remove-keyring` to remove it. Your log looks remarkably similar to how I'd expect it to look if the password was wrong.

**Comment by susenstoob** [comment]
> Can you set `debug_logging=true` in your `/config/icloudpd.conf` file and grab another log?
> 
> Also, have you changed your password recently? You'll need to run `sync-icloud.sh --remove-keyring` to remove it. Your log looks remarkably similar to how I'd expect it to look if the password was wrong.

No pass change and I just verified I was able to log into icloud.com with that same pass. I changed the logging and did a remove keyring and re-initialize. It appears to be going through the "first" sync and then I will let you know what it looks like when it finishes and synca again tomorrow.

Thanks for all your help!

**Comment by susenstoob** [comment]
That did it! My 2fa token has now been accepted for 3 additional post initial syncs. Thanks for working through this with me!

**Comment by boredazfcuk** [comment]
Awesome. Thanks for letting me know and coming back to close the issue.
